### ISSUE TITLE
FR5 - Master Repair Library

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#11]
|FR5. Master Library| 
|---| 
|**Goal**: FR5 provides the user with a list of repairs| 
|**Stakeholders:** Customers| 
| **Description:** Users have the option to select and search from a general library of repairs.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 4 |

**Comment by Jbrooks00** [comment]
This was not completed as we did not have time to complete.
