### ISSUE TITLE
FR10 - Review a mechanic

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#12]
|FR10. Reviews System| 
|---| 
|**Goal**: FR10 enables customers to post reviews based on customer experience.| 
|**Stakeholders:** Customers and Contractors| 
| **Description:** Customers will have the option of leaving a review regarding the service received.| 
| **Origin:** Introduced after discussing work flow completion.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 5 |

**Comment by Jbrooks00** [comment]
Users can review a public page in the view community page, the can directly contact the user as well.
