### ISSUE TITLE
FR11- Google Maps 

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#14]
|FR11. Google Maps Implementation| 
|---| 
|**Goal**: FR11 provides the user a discounted service| 
|**Stakeholders:** Customers and Contractors| 
| **Description:** All users will be able to use a google maps api to view nearby mechanics, and mechanic shops. Based off of inputted zipcode. | 
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 5 |

**Comment by Jbrooks00** [comment]
Completed!
