### ISSUE TITLE
FR12 - Authentic Traffic

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#15]
|FR12. Authentic User Traffic Tracker|  
|---| 
|**Goal**: FR12 will collect platform wide activity| 
|**Stakeholders:** Customers, Contractors| 
| **Description:** The application will track the number of authentic users throughout a 24 hour period. | 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 4 |

**Comment by Jbrooks00** [comment]
Our database, firebase tracks user activity data, implemented via timestamp function via chatservice.
