### ISSUE TITLE
FR15 - Repair Status

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#16]
|FR15. Repair Status| 
|---| 
|**Goal**: FR15 notifies the customer the status of their repair.| 
|**Stakeholders:** Customers and Contractors|| 
| **Description:** Contractors can keep the customers updated on their status and duration remaining on the repair. Contractors have a notes field to be stored and displayed to customer.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 4 |

**Comment by Jbrooks00** [comment]
This issue was not completed because of time constraints.
