### ISSUE TITLE
FR13 - Contractor Profiles

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#17]
|FR13. Contractor Community Profiles|  
|---| 
|**Goal**: FR13 Provide the users with a profile of the Contractor | 
|**Stakeholders:** Contractors| 
| **Description:** The contractor will have a mandatory “Community Profile” creation page, including description, and which brand they prefer.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 4 |

**Comment by Jbrooks00** [comment]
* Going to create 'Publish-post' service that allows a contractor roles to 'edit' a post. 
* The post will display blurb and preferred manufacturer.
*  The post page will be editable in my-account, update dynamically to firebase. 
* A separate page for *tbdName will display a "collection" of  saved 'public-posts page'.
*  A separate *view individual page* will display a contractors specified post.

**Comment by Jbrooks00** [comment]
*  '/editMyPage' that allows a user to update their "Community Profile" with new fields.
*  Upon user registration a 'user' role is applied to their account
*  Figuring out a way to implement a 'request' to '/editMechanicPage'....this page upon submission assigns a 'mechanic' role
* '/viewMyPage' displays both 'CommunityProfile' and 'Users' collection from firebase. While keeping current role

**Comment by Jbrooks00** [comment]
Updated my methods and html into navbar my-account page.
