### ISSUE TITLE
FR14 - Customer Vehicle Profile

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#18]
|FR14. Customer Vehicle Profile|
|---| 
|**Goal**: FR14 Determines customers car information.| 
|**Stakeholders:** Customers| 
| **Description:** Allows the customer to determine what year, make, and model car they have. | 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 2 |

**Comment by avlad83** [comment]
This has dependencies related to issues addressed in Sprint 3

**Comment by JimDUc** [comment]
Implemented Customer Vehicle Profile, user can now add the year, make, model, and color to their profile. From there, it will save within the database and pull the data back depending on which user is logged in.
