### ISSUE TITLE
NFR1. Privacy Policy

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#19]
|NFR1. Privacy Policy|
|---| 
|**Goal**: NFR1 Terms and agreements that the user must agree upon. | 
|**Stakeholders:** Customers and Contractors | 
| **Description:** Written terms and agreement, users must be disclosed with all terms and agreements upon registration.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1 |

**Comment by JimDUc** [comment]
Privacy Policy uploaded to Go-Mechanic page. Redirected linked. Upon signing up, user's are prompted right before the sign up button that by signing up they are agreeing to our TOS and Privacy Policy.
