### ISSUE TITLE
FR2 - Email Verification

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#2]
|FR2. Two-way authentication | 
|---| 
|**Goal**: FR2 creates a secure login| 
**Stakeholders:** All users| 
| **Description:** There will be an email verification that is required once a user registers. The user will have to confirm login from a third-party app and/or email in order to be granted access. Upon confirmation, the user will be logged into the app.| 
| **Origin:** Discussed as a group after lecture| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022|
|  **Priority:** 3|

**Comment by Jbrooks00** [comment]
Story points: 4

**Comment by JimDUc** [comment]
Implemented email verification, once user signs up they will be sent an one-time email verification to the email that they registered with. Upon attempting to log in, the system will check if they have verified their email not or yet; if no, the system will send a notification to the user to verify their email as well as send another verification email just in case they never received the first one. If user have verified then they will be allowed to log in successfully.
