### ISSUE TITLE
NFR2. Compatibility 

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#20]
|NFR2. Compatibility|
|---| 
|**Goal**: NFR2 Ensure device compatibility| 
|**Stakeholders:** Customers and Contractors | 
| **Description:** Ensure the resizing compatibility for mobile and desktop devices on browser platform.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1 |

**Comment by avlad83** [comment]
This requirement was labeled as bug because resizing does work smoothly for mobile devices.
To be determined if the requirement needs to be revised or addressed to match the direction of the project.
