### ISSUE TITLE
NFR3. Localization

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#21]
|NFR3. Localization|
|---| 
|**Goal**: NFR3 will identify region and | 
|**Stakeholders:** Customers and Contractors | 
| **Description:**  Users will input zip code onto their profile to identify the region. Sensitive data.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1 |

**Comment by Jbrooks00** [comment]
Implemented upon second sprint, adding more fields to user profile.
