### ISSUE TITLE
NFR4. Usability

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#22]
|NFR4. Usability| 
|---| 
|**Goal**: NFR4 will maintain the user interface| 
|**Stakeholders:** Customers and Contractors | 
| **Description:** After an account has been registered for a month, upon visiting the site they will be greeted with a user experience scale 1-10, as well as a  non required text box to be filled out. | 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1 |

**Comment by Jbrooks00** [comment]
Image size was not of importance due to the complexity of requirements.
