### ISSUE TITLE
NFR5. Scalability

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#24]
|NFR5. Scalability|  
|---| 
|**Goal**: NFR5 will scale the website to a broader audience.| 
|**Stakeholders:** Customers and Contractors | 
| **Description:** Provide a small <1% screen filled advertisement banner placement, Allow for images to be displayed. | 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1 |

**Comment by Jbrooks00** [comment]
Vlad had implemented space into the homepage.
