### ISSUE TITLE
FR9 - Global homepage

### ISSUE THREAD

**Issue by Jbrooks00** [WSU-4110/Go-Mechanic#26]
|FR9. Homepage|
|---| 
|**Goal**: Create a homepage | 
|**Stakeholders:** Customers and Contractors | 
| **Description:** Un registered and registered users will be able to access a homepage.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1 |

**Comment by avlad83** [comment]
Homepage was created in Sprint 1.
Will be updated as necessary throughout the project.
