### ISSUE TITLE
FR16 - Customer Profile

### ISSUE THREAD

**Issue by Jbrooks00** [WSU-4110/Go-Mechanic#27]
<html><body>

Goal: FR16 Determines the customers personal information
--
Stakeholders: Customers
Description: Allows the customer to determine contact information. nested inside anthonys, my account page. 
Origin: Based on initial project specification document, team members came up with this description during the first meeting.
Version: 1.0
Date: 10/18/2022
Priority: 2

</body>
</html>

**Comment by avlad83** [comment]
This has dependencies on issue that will be addressed in Sprint 3

**Comment by Jbrooks00** [comment]
> This has dependencies on issue that will be addressed in Sprint 3

We are addressing the dependency issue with jims email verification, I think its because we dont have the display name passed properly. I registered a user and verified the email, noticed the 'name' I had inputted on the sign-up page, did not properly update or save to firebase.

**Comment by Jbrooks00** [comment]
An individuals profile is viewable in dashboard, the communityPage also implements customers and contractors. Future implementation could use sorting, filter option in search bar.
