### ISSUE TITLE
FR3 - Category Repair

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#4]
|FR3. Category Repair|
|---| 
|**Goal**: FR3 provides users with general repair categories.| 
**Stakeholders:** Customer| 
| **Description:** The registered user will the select a general repair category, leading them to capable contractors profiles.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022 |
|  **Priority:** 2 |

**Comment by avlad83** [comment]
Repair results page is created by the table displays all users at this time. Filtering by role/mechanic and creation of skill category needed to fully display category of repair. Time constraints prevented further development.
