### ISSUE TITLE
FR4 - Mechanic by Manufacturer 

### ISSUE THREAD

**Issue by JimDUc** [WSU-4110/Go-Mechanic#5]
|FR4. Mechanic by Manufacturer|
|---| 
|**Goal**: FR4 Provides registered users with mechanics.| 
|**Stakeholders:** Customers and Contractors | 
| **Description:** User is displayed with a list of mechanics with certain 'brand' keyword, added to contractor bio.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. | 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 2|

**Comment by Jbrooks00** [comment]
I think this will utilize the 'screen' import or similar to peek into 'public-public' posts for keyword.

**Comment by Jbrooks00** [comment]
Current state: url '/testing' displays all users, a functional search button displays a username and role. I added a description option for searching the field.

Upon a user clicking a username, they are routed to inbox with a new chat created for them with their specified user.

**Comment by Jbrooks00** [comment]
Current state: The implementation of this resides within the my-account side navigation as the GoMechanic-Community
