### ISSUE TITLE
FR6 - Search Mechanic

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#7]
|FR6. Search Mechanic to contact|
|---| 
|**Goal**: FR6 allows customers to search.| 
|**Stakeholders:** Customer and Contractor| 
| **Description:** A user can search a name in inbox to contact a contractor.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 4 |

**Comment by Jbrooks00** [comment]
Users are able to contact mechanic via chat service.

**Comment by Jbrooks00** [comment]
Update: Users can view mechanics profiles and message directly.
