### ISSUE TITLE
FR7 - Sign out

### ISSUE THREAD

**Issue by ga6699** [WSU-4110/Go-Mechanic#8]
|FR7. Transaction types| 
|---| 
|**Goal**: FR7 enables the customers to log out of their account. | 
|**Stakeholders:** Customers and Contractors | 
| **Description:** There shall be the option in the nav-bar to log out of the account.| 
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.| 
| **Version:** 1.0  | 
|**Date:** 09/21/2022| 
|  **Priority:** 1|

**Comment by Jbrooks00** [comment]
Implemented
